# Generated by Django 5.2.1 on 2025-05-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agalya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
    ]
