# Generated by Django 5.2.1 on 2025-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalya', '0003_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
