# Generated by Django 5.2.1 on 2025-05-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalya', '0004_alter_biodata_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
